import test from "node:test";
import assert from "node:assert/strict";
import { ingestPortfolioText, fingerprintFromPortfolio } from "../dist/portfolio/index.js";
import { createEvidenceGraph } from "../dist/evidence/index.js";
import { versionFingerprint } from "../dist/versioning.js";
import { analyzeGitHub } from "../dist/github/index.js";
import { createFingerprint } from "../dist/fingerprint/create.js";
test("portfolio ingestion creates project evidence",()=>{const p=ingestPortfolioText("AURELIS Wallet\nTypeScript Next.js Web3 automation\n\nPharmaTrace\nHealthcare pharmaceutical blockchain");assert.equal(p.projects.length,2);assert.ok(p.projects[0].technologies.includes("typescript"));});
test("portfolio evidence becomes a fingerprint",()=>{const p=ingestPortfolioText("AI Evaluator\nAI data research");const f=fingerprintFromPortfolio(p);assert.ok(f.skills.length>0);});
test("GitHub analysis creates evidence-backed fingerprint",()=>{const f=analyzeGitHub({username:"x",repositories:[{name:"x",fullName:"x/x",url:"https://github.com/x/x",language:"TypeScript",topics:["automation","web3"]}]});assert.ok(f.roles.includes ? false : true);assert.ok(f.evidence?.length===1);});
test("evidence graph links corroborating signals",()=>{const g=createEvidenceGraph("c",[{source:"cv",title:"CV",signals:["typescript"],confidence:.8},{source:"github",title:"Repo",signals:["typescript"],confidence:.9}]);assert.equal(g.edges.length,2);});
test("fingerprint versioning tracks changes",()=>{const a=createFingerprint({kind:"candidate",skills:["typescript"]});const b=createFingerprint({kind:"candidate",skills:["typescript","python"]});const v=versionFingerprint(b,versionFingerprint(a));assert.equal(v.version,2);assert.ok(v.changes.includes("skills"));});
