async function loadArchive(){try{const r=await fetch("/api/archive");if(!r.ok)return;const body=await r.json();data.archive=(body.archive||[]).map(a=>({id:a.id,title:a.title,company:a.company||"",url:a.url||"",cv:a.cv_name||a.cv_id||"CV",cvId:a.cv_id||"",coverLetter:a.cover_letter||"",answers:Array.isArray(a.answers)?a.answers:[],status:a.status,submittedAt:a.submitted_at}));save();}catch(e){}}
const seed={opportunities:[],applications:[],interviews:[],offers:[],archive:[]};
async function loadApplications(){try{const r=await fetch("/api/applications");if(!r.ok)return;const body=await r.json();data.applications=(body.applications||[]).map(a=>({id:a.id,jobId:a.job_id,title:a.jobs?.title||"Application",company:a.jobs?.company||"",cv:a.cv_id||"CV pending",status:a.status}));save();}catch(e){}}
async function loadLiveJobs(){try{const r=await fetch("/api/jobs");if(!r.ok)return;const body=await r.json();const jobs=body.jobs||[];data.opportunities=jobs.map(j=>({id:j.id,title:j.title,company:j.company||"Unknown",location:j.location||"Remote",remote:j.remote,url:j.url,score:Number(j.score||0),matchScore:Number(j.score||0),cv:j.recommended_cv_id||"CV pending",source:j.source,reasons:Array.isArray(j.reasons)?j.reasons:[]}));save();view(document.querySelector(".nav.active")?.dataset.view||"overview");$("#status").textContent="Live matches · "+jobs.length+" opportunities";}catch(e){$("#status").textContent="Dashboard offline · cached data shown";}}
const data=JSON.parse(localStorage.getItem("skillprint-dashboard")||"null")||seed;
const save=()=>localStorage.setItem("skillprint-dashboard",JSON.stringify(data));
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function stats(){return{jobs:data.opportunities.length,saved:data.opportunities.filter(x=>x.stage==="saved").length,apps:data.applications.length,interviews:data.interviews.length,offers:data.offers.length}}
function job(j){return `<div class="job"><div><strong>${esc(j.title)}</strong><div class="muted">${esc(j.company)} · ${esc(j.location)}</div><span class="pill">${esc(j.cv||j.recommendedCvId||"CV pending")}</span></div><div><div class="score">${Number(j.score??j.matchScore??0)}%</div><div class="actions"><button class="ghost" onclick="saveJob('${esc(j.id)}')">${j.stage==="saved"?"Saved":"Save"}</button><button class="primary" onclick="prepareApplication('${esc(j.id)}')">Prepare application</button><a class="primary" href="${esc(j.url)}" target="_blank" rel="noopener">Open job</a></div></div></div>`}
function overview(){const s=stats();return `<div class="grid stats">${Object.entries({Matches:s.jobs,Saved:s.saved,Applications:s.apps,Interviews:s.interviews,Offers:s.offers}).map(([k,v])=>`<div class="card stat"><span class="muted">${k}</span><b>${v}</b></div>`).join("")}</div><div class="grid two"><div class="card"><p class="eyebrow">TOP MATCHES</p><div class="list">${data.opportunities.slice().sort((a,b)=>(b.score??b.matchScore??0)-(a.score??a.matchScore??0)).slice(0,10).map(job).join("")||'<div class="empty">Run the personal job search to populate this dashboard.</div>'}</div></div><div class="card"><p class="eyebrow">RECENTLY SENT</p><div class="list">${data.archive.slice().reverse().slice(0,5).map(a=>`<div class="application"><div><strong>${esc(a.title)}</strong><div class="muted">${esc(a.company)}</div></div><button class="ghost" onclick="showArchive('${esc(a.id)}')">View copy</button></div>`).join("")||'<div class="empty">No applications sent yet.</div>'}</div></div></div>`}
function tracker(items,empty){return `<div class="card">${items.length?items.map(x=>`<div class="application"><div><strong>${esc(x.title||x.jobTitle)}</strong><div class="muted">${esc(x.company||"")}</div></div><span class="pill">${esc(x.status||"open")}</span></div>`).join(""):`<div class="empty">${empty}</div>`}</div>`}
function view(name){const title={overview:"Your job hunt, in one place.",opportunities:"Ranked opportunities",applications:"Application queue",archive:"Every application you sent",interviews:"Interview tracker",offers:"Offer tracker"}[name];$("#title").textContent=title;let html="";if(name==="overview")html=overview();if(name==="opportunities")html=`<div class="card"><p class="eyebrow">MATCHED OPPORTUNITIES</p>${data.opportunities.slice().sort((a,b)=>(b.score??b.matchScore??0)-(a.score??a.matchScore??0)).map(job).join("")||'<div class="empty">No matches yet.</div>'}</div>`;if(name==="applications")html=`<div class="card"><p class="eyebrow">APPLICATIONS</p>${data.applications.map(a=>`<div class="application"><div><strong>${esc(a.title)}</strong><div class="muted">${esc(a.company)} · ${esc(a.cv)}</div></div><span class="pill">${esc(a.status)}</span></div>`).join("")||'<div class="empty">No applications yet.</div>'}</div>`;if(name==="archive")html=`<div class="card"><p class="eyebrow">SUBMISSION ARCHIVE</p><p class="muted">Skillprint keeps the exact CV, cover letter and answers used for each submission.</p>${data.archive.map(a=>`<div class="application"><div><strong>${esc(a.title)}</strong><div class="muted">${esc(a.company)} · ${esc(a.submittedAt)}</div></div><button class="primary" onclick="showArchive('${esc(a.id)}')">View exactly what was sent</button></div>`).join("")||'<div class="empty">Nothing archived yet.</div>'}</div>`;if(name==="interviews")html=tracker(data.interviews,"No interviews scheduled.");if(name==="offers")html=tracker(data.offers,"No offers recorded.");$("#view").innerHTML=html;if(name==="applications")addApprovalControls()}
window.updateApplication=async(id,status)=>{const r=await fetch("/api/applications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:id,status:status})});const body=await r.json();if(!r.ok){alert(body.error||"Could not update application.");return}await loadApplications();view("applications")};
window.addApprovalControls=()=>{const rows=document.querySelectorAll("#view .application");rows.forEach((row,i)=>{const app=data.applications[i];if(!app||app.status!=="pending_approval"||row.querySelector(".approval-actions"))return;const box=document.createElement("div");box.className="approval-actions";const approve=document.createElement("button");approve.className="primary";approve.textContent="Approve";approve.onclick=()=>updateApplication(app.id,"approved");const reject=document.createElement("button");reject.className="ghost";reject.textContent="Reject";reject.onclick=()=>updateApplication(app.id,"rejected");box.append(approve,reject);row.appendChild(box)});};
window.saveJob=async id=>{const j=data.opportunities.find(x=>x.id===id);if(!j)return;j.stage="saved";save();view("opportunities")};
window.prepareApplication=async id=>{const j=data.opportunities.find(x=>x.id===id);if(!j)return;const r=await fetch("/api/applications/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({job_id:j.id})});const body=await r.json();if(!r.ok){alert(body.error||"Could not prepare application.");return}await loadApplications();view("applications");};
window.showArchive=id=>{const a=data.archive.find(x=>x.id===id);if(!a)return;$("#dialogTitle").textContent=a.title;$("#dialogBody").textContent=[`Company: ${a.company}`,`Submitted: ${a.submittedAt}`,`Application URL: ${a.url}`,`CV used: ${a.cv} (${a.cvId})`,`Status: ${a.status}`,`\n--- COVER LETTER ---\n${a.coverLetter||""}`,`\n--- ANSWERS ---\n${(a.answers||[]).map(x=>x[0]+": "+x[1]).join("\n")}`].join("\n");$("#archiveDialog").showModal()};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");view(b.dataset.view)});
$("#refresh").onclick=()=>{view(document.querySelector(".nav.active").dataset.view);loadLiveJobs();loadApplications();loadArchive()};$("#closeDialog").onclick=()=>$("#archiveDialog").close();view("overview");loadLiveJobs();loadApplications();loadArchive();

// Supabase account and Gmail OAuth controls.
(async function initAccountAndGmail(){
 const panel=document.querySelector("#authPanel"),gmailPanel=document.querySelector("#gmailPanel"),message=document.querySelector("#authMessage"),connect=document.querySelector("#gmailConnect"),signOut=document.querySelector("#signOut");
 const setMessage=(text)=>{if(message)message.textContent=text};
 let client=null,session=null;
 function showSignedIn(s){session=s;panel.hidden=!!s;gmailPanel.hidden=!s;connect.hidden=!s;signOut.hidden=!s;if(s){setMessage("Signed in as "+(s.user?.email||"your account"));refreshGmailStatus()}else{setMessage("");document.querySelector("#gmailStatus").textContent="Not connected";document.querySelector("#gmailMessage").textContent="Sign in to connect Gmail."}}
 try{
  // Publishable keys are designed for browser use. This fallback prevents a missing
  // Vercel environment variable from disabling account creation.
  const config={supabaseUrl:"https://ofdvgipsgfrmgqezabgy.supabase.co",supabasePublishableKey:"sb_publishable_ryR2gcMXIpD6dQK8RXJBZQ_a0Zdr2L-"};
  try{
   const r=await fetch("/api/config",{cache:"no-store"});
   if(r.ok){const serverConfig=await r.json();if(serverConfig.supabaseUrl&&serverConfig.supabasePublishableKey)Object.assign(config,serverConfig);}
  }catch(_e){/* Continue with the public fallback configuration. */}
  if(!window.supabase?.createClient)throw new Error("The authentication library could not load. Check your connection and refresh.");
  client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const {data,error}=await client.auth.getSession();if(error)throw error;showSignedIn(data.session);
  client.auth.onAuthStateChange((_event,newSession)=>{session=newSession;showSignedIn(newSession)});
 }catch(e){setMessage(e.message||"Could not initialize sign-in.");}
 document.querySelector("#authForm")?.addEventListener("submit",async e=>{e.preventDefault();if(!client)return setMessage("Authentication is not configured. Check Vercel settings.");const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value;setMessage("Signing in…");const {data,error}=await client.auth.signInWithPassword({email,password});if(error){setMessage(error.message);return}showSignedIn(data.session);});
 document.querySelector("#createAccount")?.addEventListener("click",async()=>{if(!client)return setMessage("Authentication is not configured.");const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value;if(!email||password.length<6)return setMessage("Enter your email and a password of at least 6 characters.");setMessage("Creating account…");const {data,error}=await client.auth.signUp({email,password});if(error){setMessage(error.message);return}if(data.session){showSignedIn(data.session);setMessage("Account created and signed in.")}else setMessage("Account created. Check your email to confirm it, then sign in.");});
 connect?.addEventListener("click",async()=>{if(!session?.access_token)return setMessage("Sign in before connecting Gmail.");connect.disabled=true;connect.textContent="Opening Google…";try{const r=await fetch("/api/gmail/connect",{method:"POST",headers:{authorization:"Bearer "+session.access_token}});const body=await r.json();if(!r.ok)throw new Error(body.error||"Could not start Gmail connection.");window.location.assign(body.authorizationUrl)}catch(e){document.querySelector("#gmailMessage").textContent=e.message||"Could not connect Gmail."}finally{connect.disabled=false;connect.textContent="Connect Gmail"}});
 signOut?.addEventListener("click",async()=>{if(client)await client.auth.signOut();showSignedIn(null)});
 const result=new URLSearchParams(window.location.search).get("gmail");if(result){const text={connected:"Gmail connected successfully.",cancelled:"Gmail connection was cancelled.",invalid_state:"The Gmail connection expired or could not be verified. Try again.",missing_code:"Google did not return an authorization code.",error:"Gmail connection failed. Check Vercel function logs and environment settings."}[result]||"Gmail connection finished.";const gm=document.querySelector("#gmailMessage");if(gm)gm.textContent=text;history.replaceState({},document.title,window.location.pathname);if(result==="connected"&&session)setTimeout(refreshGmailStatus,300)}
})();
